repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: '^.*\.py$'
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'  # Use the latest revision
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [--max-line-length=200]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^tests/fixtures/
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        args: [
            --application-directories, '.:src',
            --py38-plus,
            --add-import, 'from __future__ import annotations',
        ]
