repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
        name: Ruff
        stages: [commit]
        additional_dependencies:
          - ruff[fix]
        args:
          - --fix
          - --exit-zero
          - --ignore=E501,D103
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Flake8
        stages: [commit]
        additional_dependencies:
          - flake8
        args:
          - --ignore=E501,D103,E231